### ISSUE TITLE
Its use needed to be explained in detail.

### ISSUE THREAD

**Issue by mashunterbd** [IamCOD3X/Android-Kernel-Compiling-Stuff#1]
Since the script is yours you will understand it very easily. But for newbies it will be very difficult to understand. So it would be better to combine the details, how to use, where to use which script, please explain.

**Comment by IamCOD3X** [comment]
The scripts are for my personal use. But you can join us on our Telegram Group - [ViP3R-KERNELs](https://t.me/ViPER_KERNELs) if you wanna ask little stuff.

**Comment by mashunterbd** [comment]
> The scripts are for my personal use. But you can join us on our Telegram Group - [ViP3R-KERNELs](https://t.me/ViPER_KERNELs) if you wanna ask little stuff.

Oh, it's okay.
